export { default as ArtistQuery } from './artist'
export { default as searchArtistQuery } from './searchArtist'
export { default as similarArtistsQuery } from './similarArtists'
export { default as artistTracksQuery } from './artistTracks'
export { default as artistAlbumsQuery } from './artistAlbums'
export { default as albumQuery } from './album'
